server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-03-30T21:14:59.079863600+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+
            #- Host=**.atguigu.com
            #- Query=username,\d+
            #- RemoteAddr=192.168.1.3/30
            - My=diamod
#            - name: My
#              args:
#                userType: diamod



        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        - id: pay_routh3 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            #- Path=/XYZ/abc/{segment}             # 断言，路径相匹配的进行路由
            #- path=/gateway/filter
            - Path=/pay/gateway/filter/**
          filters:
#            - PrefixPath=/pay
            #- SetPath=/pay/gateway/{segment}
            - RedirectTo=302, http://www.atguigu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/
#            - AddRequestHeader=X-Request-atguigu1, blue
#            - AddRequestHeader=X-Request-atguigu2, 111
#            - RemoveRequestHeader=X-Request-atguigu2
#            - RemoveRequestHeader=sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,tttttt
#            - AddRequestParameter=customerId,9527001
#            - RemoveRequestParameter=customerName
            #- AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
            #- SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
            #- RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除

